name: Lint and Format

on:
  push:
    paths:
      - '**.ts'
      - '**.js'
  workflow_dispatch:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        run: curl -fsSL https://deno.land/x/install/install.sh | sh; deno lint
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run formatter
        run: curl -fsSL https://deno.land/x/install/install.sh | sh; deno fmt
