name: Lint and Format

on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.md'
      - '**.json'
      - '**.jsonc'
  workflow_dispatch:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out repository code"
        uses: actions/checkout@v3

      - name: "Install Deno"
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export DENO_INSTALL="~/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
      
      - name: Run linter
        run: deno lint
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out repository code"
        uses: actions/checkout@v3

      - name: "Install Deno"
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export DENI_INSTALL="~/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
        
      - name: Run formatter
        run: deno fmt
